**Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно**

In [1]:
import numpy as np
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


**Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1**

In [2]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [3]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [4]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [5]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [7]:
a.resize(12, 1)
print(a)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


**Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).**

In [15]:
a.reshape(-1, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [9]:
a.reshape(4, -1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [10]:
a.reshape(12, -1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [13]:
np.reshape(a, (-1, 6))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [16]:
np.reshape(a, (-1, 2))

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

**Нет**

In [17]:
a.ndim

2

_Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив._

In [18]:
a = np.random.randn(3, 4)
print(a)

[[-0.79658434 -1.60376043  1.11569377 -0.3835366 ]
 [ 0.4655534   0.89423762  1.19966204  0.37578096]
 [ 0.711216   -1.05502855 -1.25408142  0.87498346]]


In [19]:
b = a.flatten()
print(b)

[-0.79658434 -1.60376043  1.11569377 -0.3835366   0.4655534   0.89423762
  1.19966204  0.37578096  0.711216   -1.05502855 -1.25408142  0.87498346]


In [20]:
a.size == b.size

True

**Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2**

In [21]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


**Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?**

In [22]:
b = np.arange(20, 1, -2)
print(b)

[20 18 16 14 12 10  8  6  4  2]


In [24]:
np.array_equal(a, b)

True

В обоих случаях получаются одинаковые массивы

**Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.**


In [27]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
print('Массив a ', a, sep='\n')
print('Массив b ', b, sep='\n')

Массив a 
[[0. 0.]
 [0. 0.]]
Массив b 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [28]:
v = np.concatenate((a, b), axis = 0)
print(v)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [29]:
v.size

10

**Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.**

In [30]:
a = np.arange(0, 12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [31]:
A = a.reshape(4, 3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


**Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.**

In [32]:
At = A.transpose()
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [33]:
B = np.dot(A, At)
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


Какой размер имеет матрица B?

In [34]:
B.size

16

Получится ли вычислить обратную матрицу для матрицы B и почему?

**Вычислить обратную матрицу для B невозможно, т.к. определитель матрицы B равен 0**

In [35]:
np.linalg.det(B)

0.0

**Инициализируйте генератор случайных числе с помощью объекта seed, равного 42**

In [41]:
np.random.seed(42)

**Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.**

In [44]:
 c = np.arange(16)
np.random.shuffle(c)
c

array([ 0,  1,  5, 14, 13, 11,  8,  9,  2, 15,  4,  7, 10, 12,  3,  6])

**Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.**


In [45]:
C = c.reshape((4, 4))
print(C)

[[ 0  1  5 14]
 [13 11  8  9]
 [ 2 15  4  7]
 [10 12  3  6]]


In [46]:
D = 10 * C + B
print(D)

[[  5  24  73 172]
 [144 160 166 212]
 [ 43 236 189 282]
 [132 242 242 362]]


**Вычислите определитель, ранг и обратную матрицу D_inv для D.**

In [48]:
np.linalg.det(D)

8045799.99999996

In [50]:
 D_rank = np.linalg.matrix_rank(D)
D_rank

4

In [49]:
D_inv = np.linalg.inv(D)
print(D_inv)

[[-0.05146536 -0.0877203  -0.06485371  0.12634667]
 [-0.06679013 -0.11426086 -0.06294216  0.14768202]
 [ 0.19167765  0.36821447  0.22556365 -0.4824281 ]
 [-0.06472197 -0.13778369 -0.0850655   0.1804718 ]]


**Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы.**

In [51]:
D_inv[D_inv <= 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 1., 1., 0.],
       [0., 0., 0., 1.]])

**С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.**

In [56]:
E = np.where(D_inv, B, C)
print(E)

[[  0   1   5  32]
 [ 13  11   8 122]
 [ 23  86 149   7]
 [ 10  12   3 302]]
